services:
  postgres:
    image: postgres:16-alpine
    container_name: konslo_db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=konslo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rust-app:
    build: .
    container_name: konslo_backend
    environment:
      - DATABASE_URL=postgres://postgres:admin@postgres:5432/konslo_dev
    ports:
      - "3001:3000"
    depends_on:
      - postgres
volumes:
  postgres_data: